# Generated by Django 2.2 on 2019-04-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='material_pics')),
                ('type_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.Type')),
            ],
        ),
    ]
