# Generated by Django 2.2 on 2019-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='image',
        ),
    ]
