# Generated by Django 2.2 on 2019-04-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_code_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id_waste', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('utilization', models.TextField()),
                ('image', models.ImageField(default='default', upload_to='material_pics')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='materials.Code')),
            ],
        ),
    ]
