# Generated by Django 2.2 on 2019-05-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id_station', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=20)),
                ('phone_numbers', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('working_hours', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
