# Generated by Django 2.2 on 2019-05-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='Choice')),
                ('position', models.IntegerField(verbose_name='position')),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='materials.Question')),
            ],
            options={
                'ordering': ('position',),
                'unique_together': {('q', 'position'), ('q', 'choice')},
            },
        ),
    ]
