# Generated by Django 2.2 on 2019-05-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_auto_20190503_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='q',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='materials.Question'),
        ),
    ]
