# Generated by Django 2.2 on 2019-05-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20190503_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterField(
            model_name='choice',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
    ]
