# Generated by Django 2.2 on 2019-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20190503_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='id_question',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
