# Generated by Django 2.2 on 2019-05-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0010_auto_20190503_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
