# Generated by Django 2.2 on 2019-05-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20190503_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('q', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50)),
                ('position', models.IntegerField()),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='materials.Question')),
            ],
        ),
    ]
