# Generated by Django 2.2 on 2019-05-03 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0012_choice_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('position',)},
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('q', 'choice'), ('q', 'position')},
        ),
    ]
