# Generated by Django 2.2 on 2019-05-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0013_auto_20190504_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.CharField(max_length=200),
        ),
    ]
