# Generated by Django 2.2 on 2019-05-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_auto_20190504_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
