# Generated by Django 2.2 on 2019-05-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20190430_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_last_access',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
