# Generated by Django 2.2 on 2019-05-02 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190502_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_last_access',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
