# Generated by Django 2.2 on 2019-05-02 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190502_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_last_access',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 23, 5, 2, 227410)),
        ),
    ]
